forge 'https://forgeapi.puppetlabs.com'

mod 'mhuffnagle/make',
  :git => 'https://github.com/Element84/puppet-make.git'

mod 'puppetlabs/ntp',
  :git => 'https://github.com/puppetlabs/puppetlabs-ntp.git'

mod 'puppetlabs/vcsrepo',
  :git => 'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'

mod 'puppetlabs/firewall',
  :git => 'https://github.com/puppetlabs/puppetlabs-firewall.git',
  :ref => '1.1.3'

mod 'puppetlabs/inifile',
  :git => 'https://github.com/puppetlabs/puppetlabs-inifile.git',
  :ref => '1.1.3'

mod 'zack/r10k',
  :git => 'https://github.com/acidprime/r10k.git'
