---
# Boxes
# Updated: 2014-11-26 --- PT
boxes:

 'fs_centos-65-x64-vbox4316-nocm': 'http://file.azcender.com/boxes/fs_centos-65-x64-vbox4316-nocm.box'
 'fs_centos-7-x64-vbox4320-nocm': 'http://file.azcender.com/boxes/fs_centos-7-x64-vbox4320-nocm.box'
 'fs_ubuntu-server-14041-x64-vbox4316-nocm': 'http://file.azcender.com/boxes/fs_ubuntu-server-14041-x64-vbox4316-nocm.box'
 'fs_win-2012r2-standard-amd64-vbox4316-nocm': 'http://file.azcender.com/boxes/fs_win-2012r2-standard-amd64-vbox4316-nocm.box'
