---
# Boxes from http://puppet-vagrant-boxes.puppetlabs.com/
# Updated: 2014-08-26
boxes:
  'centos-64-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/centos-64-x64-vbox4210-nocm.box'
  'ubuntu-server-12042-x64-vbox4210-nocm': 'http://puppet-vagrant-boxes.puppetlabs.com/ubuntu-server-12042-x64-vbox4210-nocm.box'
  'win-2012r2-standard-amd64-vbox4314-nocm': 'https://drive.google.com/a/fullfrontalingenuity.com/uc?export=download&confirm=FdzM&id=0B5hU98NHqO-wcUJNZVppTDBWUFE'
