---
# Boxes
# Updated: 2015-05-07 --- PT
#

boxes:
  puppetlabs/centos-6.5-64-nocm:
    'https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.5-64-nocm'
  puppetlabs/centos-6.6-64-nocm:
    'https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-64-nocm'
  puppetlabs/centos-7.0-64-nocm:
    'https://atlas.hashicorp.com/puppetlabs/boxes/centos-7.0-64-nocm'
  fs_ubuntu-server-14041-x64-vbox4320-nocm:
    'http://file.azcender.com/boxes/fs_ubuntu-server-14041-x64-vbox4320-nocm.box'
  fs_win-2012r2-standard-amd64-vbox4316-nocm:
    'http://artifactory.azcender.com/artifactory/vagrant-local/win-2012r2-standard-amd64-nocm'
  azcender/rhel-6.6-x86_64:
    'http://file.azcender.com/boxes/rhel66.box'
  azcender/rhel-7.0-x86_64:
    'http://file.azcender.com/boxes/rhel70.box'
  centos-6.6-64-nocm:
    'http://file.azcender.com/boxes/centos-6.6-64-nocm.box'
