---
roles:
  pe-puppet-master:
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096, '--cpus', 4]
    vbguest:
      auto_update: true
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    forwarded_ports:
      - {guest: 443, host: 8443}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/puppet /usr/bin/puppet'}
      - {type: puppet, manifests_path: puppet/manifests, manifest_file: site.pp, module_path: puppet/modules, options: '--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml'}

  pe-puppet-agent-linux:
    provider:
      type: virtualbox
      gui: false
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024, '--cpus', 2]
    vbguest:
      auto_update: true
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/puppet /usr/bin/puppet'}
      - {type: puppet, manifests_path: puppet/manifests, manifest_file: site.pp, module_path: puppet/modules, options: '--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml'}

  pe-puppet-agent-windows:
    provider:
      type: virtualbox
      gui: true
      guest: windows
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 2048, '--cpus', 2]
    vbguest:
      auto_update: false
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    forwarded_ports:
      - {guest: 5985, host: 5985, id: 'winrm', auto_correct: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
