---
roles:
  pe-puppet-master:
    vbguest:
      auto_update: true
    provider:
      type: virtualbox
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 4096, '--cpus', 4]
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    forwarded_ports:
      - {guest: 443, host: 8443}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/puppet /usr/bin/puppet'}
      - {type: shell, inline: '/opt/puppet/bin/rake -f /opt/puppet/share/puppet-dashboard/Rakefile RAILS_ENV=production node:variables["master","role=master"]'}
      - {type: shell, inline: '/opt/puppet/bin/rake -f /opt/puppet/share/puppet-dashboard/Rakefile RAILS_ENV=production node:addclass[master,pe_repo::platform::el_7_x86_64]'}
      - {type: shell, inline: '/opt/puppet/bin/rake -f /opt/puppet/share/puppet-dashboard/Rakefile RAILS_ENV=production node:addclass[master,pe_repo::platform::ubuntu_1404_amd64]'}
      - {type: puppet, manifests_path: puppet/manifests, manifest_file: site.pp, module_path: puppet/modules, options: '--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml'}

  pe-puppet-agent-linux:
    vbguest:
      auto-update: true
    provider:
      type: virtualbox
      gui: false
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 1024, '--cpus', 2]
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
#     - {type: pe_bootstrap}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/puppet /usr/bin/puppet'}
      - {type: puppet, manifests_path: puppet/manifests, manifest_file: site.pp, module_path: puppet/modules, options: '--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml'}

  pe-puppet-agent-windows:
    hostname: #{name}
    guest: 'windows'
    communicator: 'winrm'
    vbguest:
      auto_update: false
    provider:
      type: virtualbox
      gui: true
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 2048, '--cpus', 2]
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    forwarded_ports:
      - {guest: 5985, host: 5985, id: 'winrm', auto_correct: true}
      - {guest: 3389, host: 8389, id: 'rdp', autocorrect: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
