---
roles:
  pe-puppet-master:
    provider:
      type: vmware_fusion
      gui: false
# Customize is for virtual box... have switched to vmware
#      type: virtualbox
#      customize:
#        - [modifyvm, !ruby/sym id, '--memory', 6144, '--cpus', 4]
      vmx:
        memsize:  5120
        numvcpus: 2
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap, role: !ruby/sym master}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/puppet /usr/bin/puppet'}
      - {type: shell, inline: 'ln -s -f /opt/puppet/bin/r10k /usr/bin/r10k'}
      - {type: puppet, manifests_path: puppet/manifests, manifest_file: site.pp,
         module_path: puppet/modules,
         options: '--verbose --debug --hiera_config /vagrant/puppet/hiera.yaml'}
      - {type: shell, inline: 'r10k deploy environment production --puppetfile'}
      - {type: shell, inline: 'r10k deploy environment hiera_production'}
      - {type: shell, inline: 'puppet agent -t'}
      - {type: shell, inline: '/usr/bin/yum clean all; /usr/bin/yum update -y;#/usr/sbin/service NetworkManager restart'}

  pe-puppet-agent-linux:
    vbguest:
      auto-update: true
    provider:
# The code below is for the original virtualbox implementaiton
#      type: virtualbox
#      gui: false
#      customize:
#        - [modifyvm, !ruby/sym id, '--memory', 1024, '--cpus', 1]
      type: vmware_fusion
      vmx:
        memsize: 1024
        numvcpus: 1
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: hosts}
      - {type: shell,
         inline: 'curl -k https://master:8140/packages/current/install.bash | sudo bash'}
      - {type: shell, inline: '/usr/bin/yum clean all; /usr/bin/yum update -y; /usr/sbin/service NetworkManager restart'}

  pe-puppet-agent-windows:
    hostname: #{name}
    guest: 'windows'
    communicator: 'winrm'
    vbguest:
      auto_update: false
    provider:
      type: virtualbox
      gui: true
      customize:
        - [modifyvm, !ruby/sym id, '--memory', 2048, '--cpus', 2]
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    forwarded_ports:
      - {guest: 5985, host: 5985, id: 'winrm', auto_correct: true}
      - {guest: 3389, host: 8389, id: 'rdp', autocorrect: true}
    provisioners:
      - {type: hosts}
      - {type: pe_bootstrap}
