---
vms:
  - name: master
#   box: fs_centos-65-x64-vbox4316-nocm
    box: fs_ubuntu-server-14041-x64-vbox4316-nocm
    roles:
      - pe-puppet-master

  - name: centos0
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: centos1
    box: fs_centos-7-x64-vbox4320-nocm 
    roles:
      - pe-puppet-agent-linux

  - name: centos2
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: centos3
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: winders0
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows

  - name: winders1
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows
