---
vms:
  - name: master
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-master

  - name: weblogic0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: jenkins0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: jenkins1
    box: puppetlabs/centos-7.0-64-nocm 
    roles:
      - pe-puppet-agent-linux

  - name: docker0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: docker1
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: haproxy0
    box:  puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat1
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: winders0
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows

  - name: winders1
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows
