---
vms:
  - name: master
    box:  fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-master

  - name: jenkins0
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: jenkins1
    box: fs_centos-7-x64-vbox4320-nocm 
    roles:
      - pe-puppet-agent-linux

  - name: docker0
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: docker1
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat0
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat1
    box: fs_centos-7-x64-vbox4320-nocm
    roles:
      - pe-puppet-agent-linux

  - name: winders0
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows

  - name: winders1
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows
