---
vms:
  - name: master
#   box: centos-64-x64-vbox4210-nocm
    box: ubuntu-server-12042-x64-vbox4210-nocm
    roles:
      - pe-puppet-master

  - name: centos0
    box: centos-64-x64-vbox4210-nocm
    roles:
      - pe-puppet-agent-linux

 - name: centos1
   box: centos-64-x64-vbox4210-nocm
   roles:
     - pe-puppet-agent-linux

  - name: centos2
    box: centos-64-x64-vbox4210-nocm
    roles:
      - pe-puppet-agent-linux

  - name: centos3
    box: centos-64-x64-vbox4210-nocm
    roles:
      - pe-puppet-agent-linux

  - name: winders0
    box: win-2012r2-standard-amd64-nocm
    roles:
      - pe-puppet-agent-windows

# - name: winders1
#   box: win-2012r2-standard-amd64-nocm
#   roles:
#     - pe-puppet-agent-windows
