---
vms:
  - name: master
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-master

  - name: rhel-master
    box: azcender/rhel-6.6-x86_64
    roles:
      - pe-puppet-master

  - name: weblogic0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-docker

  - name: database0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: oid0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: oem0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: jenkins0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: jenkins1
    box: puppetlabs/centos-7.0-64-nocm 
    roles:
      - pe-puppet-agent-linux

  - name: docker0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-docker

  - name: docker1
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-docker

  - name: haproxy0
    box:  puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat200
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat201
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat202
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat207
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat222
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat229
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat230
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat0
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: tomcat1
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - pe-puppet-agent-linux

  - name: winders0
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows

  - name: winders1
    box: fs_win-2012r2-standard-amd64-vbox4316-nocm
    roles:
      - pe-puppet-agent-windows

  - name: beaker
    box: puppetlabs/centos-7.0-64-nocm
    roles:
      - beaker
